apiVersion: apps/v1
kind: Deployment
metadata:
  name: kitchen-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kitchen-pod
  template:
    metadata:
      labels:
        app: kitchen-pod
    spec:
      containers:
      - name: kitchen-container
        image: ingjavierr/kitchen-service:latest
        ports:
        - containerPort: 8200
        imagePullPolicy: Always
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: qa
        - name: TZ
          value: America/Mexico_City
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: database
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: database
              key: POSTGRES_PASSWORD
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: database
              key: POSTGRES_DB
---
apiVersion: v1
kind: Service
metadata:
  name: kitchen-svc
spec:
  selector:
    app: kitchen-pod
  ports:
  - port: 8200
    protocol: TCP
    targetPort: 8200
  type: ClusterIP